# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftPlayground' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftPlayground

  target 'RxSwiftPlaygroundTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
  end

  target 'RxSwiftPlaygroundUITests' do
    # Pods for testing
  end

end
